name: CI/CD Golang

on:
  pull_request:
    branches: [ main ]
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Build
        run: go build ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: latest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Test with coverage
        run: go test -coverprofile=coverage.out ./...

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-results.sarif
          command: code test
      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'snyk-results.sarif'
      - name: Check for High or Critical vulnerabilities
        shell: bash
        run: |
          # Contamos cuántos resultados tienen nivel 'error' (que mapea a High/Critical en SARIF)
          ERRORS=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk-results.sarif)
          
          echo "Vulnerabilidades críticas/altas encontradas: $ERRORS"
          
          if [ "$ERRORS" -gt 0 ]; then
            echo "Error: Se encontraron $ERRORS vulnerabilidades de nivel Alto/Crítico."
            exit 1
          fi

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-results.sarif
          command: test
      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'snyk-results.sarif'
      - name: Check for High or Critical vulnerabilities
        shell: bash
        run: |
          # Contamos cuántos resultados tienen nivel 'error' (que mapea a High/Critical en SARIF)
          ERRORS=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk-results.sarif)
          
          echo "Vulnerabilidades críticas/altas encontradas: $ERRORS"
          
          if [ "$ERRORS" -gt 0 ]; then
            echo "Error: Se encontraron $ERRORS vulnerabilidades de nivel Alto/Crítico."
            exit 1
          fi
